export const facilities = [
    "Hồ bơi trong nhà",
    "Dịch vụ phòng",
    "Bữa sáng rất tốt",
    "Hồ bơi",
    "Tiện nghi BBQ",
    "2 nhà hàng",
    "Bữa sáng tuyệt vời",
    "Bữa sáng",
    "Hồ bơi - ngoài trời (dành cho trẻ em)",
    "Quầy bar",
    "Phòng không hút thuốc",
    "Chỗ đỗ xe miễn phí",
    "Thang máy",
    "Máy pha trà/cà phê trong tất cả các phòng",
    "WiFi nhanh miễn phí (329 Mbps)",
    "Chỗ đậu xe riêng",
    "Phòng gia đình",
    "Bữa sáng tốt",
    "Chỗ đỗ xe",
    "Trung tâm thể dục",
    "Tiện nghi cho khách khuyết tật",
    "Dịch vụ đưa đón sân bay (miễn phí)",
    "2 hồ bơi",
    "Chỗ đậu xe (trong khuôn viên)",
    "Giáp biển",
    "Lễ tân 24 giờ",
    "Bữa sáng xuất sắc",
    "Sân thượng / hiên",
    "Hồ bơi ngoài trời",
    "Nhà hàng",
    "Bữa sáng tuyệt hảo",
    "WiFi nhanh miễn phí (85 Mbps)",
    "WiFi miễn phí",
    "Khu vực bãi tắm riêng",
    "Xe đưa đón sân bay",
    "WiFi nhanh miễn phí (75 Mbps)",
    "Trung tâm Spa & chăm sóc sức khoẻ",
]
