export const highlights = {
    "Hoàn hảo cho kỳ nghỉ 1 đêm!": [
        "Địa điểm hàng đầu: Được khách gần đây đánh giá cao",
        "Bạn muốn ngủ thật ngon? Khách sạn này được đánh giá cao nhờ những chiếc giường thoải mái.",
        "Đồ Ăn Ngon Tuyệt: Bạn rất nên dùng các bữa ăn ở đây",
    ],
    "Khách trung thành": ["Chỗ nghỉ này có nhiều khách trở lại hơn hầu hết các chỗ nghỉ khác."],
    "Phòng có:": [
        "Hồ bơi có tầm nhìn",
        "Nhìn ra hồ",
        "Sân hiên",
        "Nhìn ra biển",
        "Nhìn ra núi",
        "Hướng nhìn sân trong",
        "Nhìn ra vườn",
        "Hướng nhìn ra đường phố yên ắng",
        "Nhìn ra hồ bơi",
        "Nhìn ra sông",
        "Nhìn ra thành phố",
        "Nhìn ra địa danh nổi tiếng",
    ],
    "Thông tin về bữa sáng": [
        "Kiểu lục địa",
        "Kiểu Ý",
        "Halal (dành cho người theo đạo Hồi)",
        "Kiêng Gluten",
        "Thực đơn chay",
        "Thực đơn chay không trứng",
        "Sữa",
        "Kiểu Á",
        "Kiểu Mỹ",
        "Tự chọn",
        "Bữa sáng mang đi",
        "Kiểu Anh/ Ai Len",
        "Kosher (dành cho người theo đạo Do Thái)",
    ],
    "Căn hộ với:": [
        "Nhìn ra biển",
        "Hướng nhìn sân trong",
        "Nhìn ra sông",
        "Sân thượng / hiên",
        "Nhìn ra hồ",
        "Nhìn ra hồ bơi",
        "Nhìn ra vườn",
        "Nhìn ra địa danh nổi tiếng",
        "Sân hiên",
        "Hồ bơi có tầm nhìn",
        "Nhìn ra núi",
        "Nhìn ra thành phố",
        "Hướng nhìn ra đường phố yên ắng",
    ],
}
