export const roomServices = {
    "Tầm nhìn": [
        "Nhìn ra biển",
        "Nhìn ra địa danh nổi tiếng",
        "Nhìn ra hồ bơi",
        "Nhìn ra núi",
        "Nhìn ra thành phố",
        "Nhìn ra vườn",
        "Hướng nhìn sân trong",
        "Tầm nhìn ra khung cảnh",
        "Nhìn ra hồ",
        "Nhìn ra sông",
    ],
    "Cửa hàng": ["Cửa hàng tạp hóa (trong khuôn viên)", "Hiệu cắt tóc/làm đẹp"],
    "Phòng ngủ": [
        "Phòng thay quần áo",
        "Tủ hoặc phòng để quần áo",
        "Giường cực dài (> 2 mét)",
        "Ra trải giường",
        "Đồng hồ báo thức",
    ],
    "Đồ ăn & thức uống": [
        "Quầy bar",
        "Giao nhận đồ tạp hóa",
        "Máy pha trà/cà phê",
        "Thực đơn ăn kiêng đặc biệt (theo yêu cầu)",
        "Bữa sáng tại phòng",
        "Bữa trưa đóng hộp",
        "Dịch vụ phòng",
        "Trái cây",
        "Bữa ăn trẻ em",
        "Rượu vang/sâm panh",
        "Máy bán hàng tự động (đồ uống)",
        "Quán cà phê (trong khuôn viên)",
        "Quầy bar (đồ ăn nhẹ)",
        "Minibar",
        "Bữa ăn tự chọn phù hợp với trẻ em",
        "Nhà hàng",
    ],
    "Chăm sóc sức khỏe": [
        "Mát-xa dành cho cặp đôi",
        "Trung tâm thể dục",
        "Phòng tắm chung",
        "Chăm sóc tóc",
        "Ô (dù) che nắng loại to",
        "Tẩy tế bào chết toàn thân",
        "Cắt tóc",
        "Quấn toàn thân",
        "Tắm suối nước nóng",
        "Dịch vụ ngâm chân",
        "Mát-xa lưng",
        "Cầu trượt nước",
        "Phòng tắm không gian mở",
        "Trị Liệu Cơ Thể",
        "Mát-xa tay",
        "Massage",
        "Tiện Nghi Spa",
        "Ghế mát-xa",
        "Dịch vụ làm móng chân",
        "Dịch vụ triệt lông",
        "Huấn luyện viên cá nhân",
        "Bồn tắm nóng/bể sục (Jacuzzi)",
        "Mát-xa đầu",
        "Chăm sóc da mặt",
        "Phòng gym",
        "Dịch vụ làm móng tay",
        "Mát-xa cổ",
        "Gói spa/chăm sóc sức khỏe",
        "Dịch Vụ Làm Đẹp",
        "Lớp thể dục",
        "Dịch vụ trang điểm",
        "Mát-xa chân",
        "Phòng tắm nắng",
        "Ghế/ghế dài tắm nắng",
        "Lớp học yoga",
        "Tạo kiểu tóc",
        "Nhuộm tóc",
        "Hồ bơi trẻ em",
        "Bồn tắm hơi/kiểu Thổ Nhĩ Kỳ",
        "Phòng xông hơi ướt",
        "Khu vực thư giãn/spa lounge",
        "Mát-xa toàn thân",
        "Liệu pháp ánh sáng",
        "Phòng gửi đồ ở spa/gym",
        "Trung tâm Spa & chăm sóc sức khoẻ",
        "Phòng xông hơi",
    ],
    "Hồ bơi ngoài trời": [
        "Bể ngâm",
        "Cầu trượt nước",
        "Dành cho mọi độ tuổi",
        "Theo mùa",
        "Giờ mở cửa",
        "Hồ bơi có tầm nhìn",
        "Hồ bơi nước mặn",
        "Ô (dù) che nắng loại to",
        "Mái che hồ bơi",
        "Khăn hồ bơi/bãi biển",
        "Hồ bơi nước nóng",
        "Quầy bar hồ bơi",
        "Đồ chơi ở hồ bơi",
        "Hàng rào quanh hồ bơi",
        "Hồ bơi trên sân thượng",
        "Ghế/ghế dài tắm nắng",
        "Chỉ dành cho người lớn",
        "Mở cửa quanh năm",
        "Hồ bơi vô cực",
        "Chỗ cạn",
    ],
    "Phòng tắm": [
        "Khăn tắm/Bộ khăn trải giường (có thu phí)",
        "Nhà vệ sinh",
        "Giấy vệ sinh",
        "Bồn tắm spa",
        "Áo choàng tắm",
        "Máy sấy tóc",
        "Bồn tắm hoặc Vòi sen",
        "Dép",
        "Vòi sen",
        "Toilet chung",
        "Phòng tắm riêng",
        "Đồ vệ sinh cá nhân miễn phí",
        "Chậu rửa vệ sinh (bidet)",
        "Toilet phụ",
        "Phòng tắm phụ",
        "Phòng tắm chung",
        "Bồn tắm",
        "Khăn tắm",
    ],
    "Chỗ đậu xe": [
        "Bãi đậu xe tiếp cận người khuyết tật",
        "Nhà để xe",
        "Dịch vụ đỗ xe cho khách",
        "Trạm sạc xe điện",
        "Chỗ đậu xe ngoài đường",
    ],
    "Dịch vụ giải trí và gia đình": [
        "Trò chơi board game/giải đố",
        "Sòng bạc",
        "Xe đẩy",
        "Nhân viên Giải trí",
        "Giải trí buổi tối",
        "Cửa an toàn cho trẻ nhỏ",
        "Sân chơi trẻ em",
        "Karaoke",
        "Dịch vụ trông giữ trẻ em",
        "Câu lạc bộ trẻ em",
        "Trò chơi Board games/giải đố",
        "Nắp che ổ cắm điện an toàn",
        "Thiết bị vui chơi ngoài trời cho trẻ em",
        "Khu vui chơi trong nhà",
        "Sách, đĩa DVD và nhạc cho trẻ em",
    ],
    "Ngoài trời": [
        "Sân hiên",
        "Bàn ghế ngoài trời",
        "Sân trong",
        "Khu vực bãi tắm riêng",
        "Sân thượng / hiên",
        "Sân hiên phơi nắng",
        "Hồ bơi riêng",
        "Giáp biển",
        "Khu vực ăn uống ngoài trời",
        "Tiện nghi BBQ",
        "Khu vực picnic",
        "Ban công",
        "Tiện nghi BBQ",
        "Lò sưởi ngoài trời",
        "Sân vườn",
    ],
    "Nhà bếp": [
        "Bếp nhỏ",
        "Máy pha Cà phê",
        "Bếp nấu",
        "Máy rửa bát",
        "Bếp chung",
        "Máy nướng bánh mỳ",
        "Bếp",
        "Máy sấy quần áo",
        "Đồ bếp",
        "Lò vi sóng",
        "Ghế cao dành cho trẻ em",
        "Ấm đun nước điện",
        "Sản phẩm lau rửa",
        "Tủ lạnh",
        "Máy giặt",
        "Lò nướng",
        "Bàn ăn",
    ],
    "Các tiện nghi khác": [
        "Phòng không hút thuốc",
        "Phòng không gây dị ứng",
        "Toilet dành cho người khuyết tật",
        "Hệ thống sưởi",
        "Chỗ ngủ cho vật nuôi",
        "Dây khẩn cấp trong phòng tắm",
        "Lối vào cho người đi xe lăn",
        "Điều hòa nhiệt độ",
        "Chỉ dành cho người lớn",
        "Toilet có sàn cao hơn",
        "Phòng cách âm",
        "Bát ăn cho vật nuôi",
        "Cấm hút thuốc trong toàn bộ khuôn viên",
        "Khu vực cho phép hút thuốc",
        "Hướng dẫn bằng âm thanh",
        "Bồn rửa mặt thấp hơn",
        "Phòng gia đình",
        "Thang máy",
        "Hỗ trợ khiếm thị: Dấu hiệu nổi",
        "Hỗ trợ khiếm thị: Braille",
        "Tiện nghi cho khách khuyết tật",
    ],
    "Dịch vụ": [
        "Giữ hành lí",
        "Tủ khóa",
        "Dịch vụ báo thức",
        "Dịch vụ đưa đón",
        "Dịch vụ báo thức",
        "Khu vực xem TV/sảnh chung",
        "Dọn phòng hàng ngày",
        "Máy bán hàng tự động (đồ uống)",
        "Cho thuê xe hơi",
        "Nhận/trả phòng cấp tốc",
        "Nhận/trả phòng riêng",
        "Fax/photocopy",
        "Dịch vụ phòng",
        "Bàn ủi li quần",
        "Máy ATM/rút tiền trong khuôn viên",
        "Lễ tân 24 giờ",
        "Dịch vụ trợ giúp đặc biệt",
        "Giặt khô",
        "Tiện nghi tổ chức hội họp/tiệc",
        "Xe đưa đón sân bay",
        "Giao nhận đồ tạp hóa",
        "Giặt ủi",
        "Thu đổi ngoại tệ",
        "Dịch vụ là (ủi)",
        "Bàn bán tour",
        "Hiệu cắt tóc/làm đẹp",
    ],
    "Khu vực phòng khách": [
        "Khu vực phòng ăn",
        "Lò sưởi",
        "Bàn làm việc",
        "Ghế sofa",
        "Khu vực tiếp khách",
    ],
    "Dịch vụ lau dọn": [
        "Giặt khô",
        "Dịch vụ là (ủi)",
        "Bàn ủi li quần",
        "Giặt ủi",
        "Dọn phòng hàng ngày",
    ],
    "Tiện ích trong phòng": [
        "Sàn lát gỗ",
        "Có phòng thông nhau qua cửa nối",
        "Không gây dị ứng",
        "Giường xếp",
        "Hệ thống cách âm",
        "Sàn lát gạch/đá cẩm thạch",
        "Giá treo quần áo",
        "Lối vào riêng",
        "Giường sofa",
        "Quạt máy",
        "Điều hòa không khí",
        "Màn chống muỗi",
        "Sàn trải thảm",
        "Bàn ủi",
        "Giá phơi quần áo",
        "Ổ điện gần giường",
        "Bàn ủi li quần",
        "Tiện nghi ủi",
        "Hệ thống sưởi",
    ],
    "Lối vào dành cho người khuyết tật": [
        "Hướng dẫn bằng âm thanh",
        "Hoàn toàn nằm ở tầng trệt",
        "Hỗ trợ khiếm thị: Braille",
        "Lối vào cho người đi xe lăn",
        "Hỗ trợ khiếm thị: Dấu hiệu nổi",
        "Các tầng trên chỉ lên được bằng cầu thang",
        "Xe lăn có thể đi đến mọi nơi trong toàn bộ khuôn viên",
        "Dây khẩn cấp trong phòng tắm",
        "Toilet dành cho người khuyết tật",
        "Các tầng trên đi lên bằng thang máy",
        "Toilet có sàn cao hơn",
        "Bồn rửa mặt thấp hơn",
        "Tiện ích hỗ trợ người khiếm thính",
    ],
    "Hồ bơi trong nhà": [
        "Chỉ dành cho người lớn",
        "Ghế/ghế dài tắm nắng",
        "Hồ bơi có tầm nhìn",
        "Mái che hồ bơi",
        "Mở cửa quanh năm",
        "Dành cho mọi độ tuổi",
        "Cầu trượt nước",
        "Khăn hồ bơi/bãi biển",
        "Quầy bar hồ bơi",
        "Theo mùa",
        "Hồ bơi vô cực",
        "Hàng rào quanh hồ bơi",
        "Hồ bơi nước mặn",
        "Hồ bơi trên sân thượng",
        "Đồ chơi ở hồ bơi",
        "Ô (dù) che nắng loại to",
        "Chỗ cạn",
        "Hồ bơi nước nóng",
        "Giờ mở cửa",
    ],
    "Phương tiện đi lại": [
        "Cho thuê xe đạp",
        "Xe đưa đón sân bay",
        "Cho thuê xe hơi",
        "Vé đi phương tiện công cộng",
        "Dịch vụ đưa đón",
    ],
    "Hoạt động": [
        "Bóng quần (Squash)",
        "Xe đạp",
        "Phi tiêu",
        "Bãi biển",
        "Giờ vàng",
        "Câu cá",
        "Lướt ván buồm",
        "Phòng chơi game",
        "Lặn",
        "Thiết bị dành cho tennis",
        "Giải trí buổi tối",
        "Cưỡi ngựa",
        "Bóng bàn",
        "Bowling",
        "Công viên nước",
        "Vũ trường/DJ",
        "Triển lãm tranh đương đại",
        "Hài độc thoại",
        "Bida",
        "Đêm phim",
        "Sòng bạc",
        "Karaoke",
        "Tiện nghi chơi thể thao dưới nước (trong khuôn viên)",
        "Bingo",
        "Nhảy/khám phá bar",
        "Câu lạc bộ trẻ em",
        "Tour/lớp về văn hóa địa phương",
        "Lớp dạy nấu ăn",
        "Thiết bị dành cho cầu lông",
        "Bắn cung",
        "Tour đi xe đạp",
        "Tour đi bộ",
        "Thể dục nhịp điệu (aerobic)",
        "Sự kiện thể thao (truyền hình trực tiếp)",
        "Bể sục",
        "Sân chơi trẻ em",
        "Sân gôn (trong vòng 3km)",
        "Ca-nô",
        "Nhân viên Giải trí",
        "Biểu diễn/nhạc sống",
        "Cho thuê xe đạp",
        "Sân gôn mini",
        "Đi bộ đường dài",
        "Lặn với ống thở",
        "Bữa tối theo chủ đề",
        "Sân tennis",
    ],
    "Ngoài trời & Tầm nhìn": [
        "Nhìn ra biển",
        "Hướng nhìn sân trong",
        "Nhìn ra vườn",
        "Nhìn ra thành phố",
        "Tầm nhìn ra khung cảnh",
        "Nhìn ra hồ",
        "Nhìn ra hồ bơi",
        "Nhìn ra địa danh nổi tiếng",
        "Nhìn ra núi",
        "Nhìn ra sông",
    ],
    "Dịch vụ & Khoản phụ": ["Quyền sử dụng Executive Lounge", "Dịch vụ báo thức"],
    "Đặc tính tòa nhà": ["Căn hộ riêng trong tòa nhà", "Song lập", "Đơn lập"],
    "Dịch vụ cho doanh nhân": [
        "Trung tâm dịch vụ doanh nhân",
        "Tiện nghi tổ chức hội họp/tiệc",
        "Fax/photocopy",
    ],
    "An ninh": [
        "Bình chữa cháy",
        "Thiết bị báo cháy",
        "Hệ thống CCTV trong khu vực chung",
        "Két an toàn",
        "Ổ khóa",
        "Báo động an ninh",
        "Thiết bị báo carbon monoxide",
        "Ổ khóa mở bằng thẻ",
        "Hệ thống CCTV bên ngoài chỗ nghỉ",
        "Bảo vệ 24/7",
    ],
    "Tổng quát": [
        "Khu vực cho phép hút thuốc",
        "Thang máy",
        "Cho thuê xe hơi",
        "Không gây dị ứng",
        "Màn chống muỗi",
        "Bát ăn cho vật nuôi",
        "Bàn ủi li quần",
        "Khu vực xem TV/sảnh chung",
        "Cấm hút thuốc trong toàn bộ khuôn viên",
        "Hệ thống cách âm",
        "Chỉ dành cho người lớn",
        "Tiện nghi cho khách khuyết tật",
        "Dịch vụ báo thức",
        "Bữa trưa đóng hộp",
        "Quyền sử dụng Executive Lounge",
        "Chăn điện",
        "Dịch vụ đưa đón",
        "Hệ thống sưởi",
        "Nhà thờ/miếu thờ",
        "Dịch vụ phòng",
        "Tiện nghi ủi",
        "Phòng cách âm",
        "Bàn ủi",
        "Hiệu cắt tóc/làm đẹp",
        "Có phòng thông nhau qua cửa nối",
        "Quạt máy",
        "Dịch vụ báo thức",
        "Sàn lát gỗ",
        "Két an toàn cỡ laptop",
        "Chỗ ngủ cho vật nuôi",
        "Xe đưa đón sân bay",
        "Điều hòa không khí",
        "Giao nhận đồ tạp hóa",
        "Phòng gia đình",
        "Sàn trải thảm",
        "Thiết bị báo carbon monoxide",
        "Phòng không gây dị ứng",
        "Lối vào riêng",
        "Điều hòa nhiệt độ",
        "Sàn lát gạch/đá cẩm thạch",
        "Cửa hàng tạp hóa (trong khuôn viên)",
        "Máy bán hàng tự động (đồ uống)",
        "Phòng không hút thuốc",
        "Máy bán hàng tự động (đồ ăn nhẹ)",
    ],
    "Khu vực chung": ["Phòng chơi game", "Khu vực xem TV/sảnh chung"],
    "Truyền thông & Công nghệ": [
        "Truyền hình cáp",
        "Đầu video",
        "Két an toàn cỡ laptop",
        "Ổ cắm cho iPod",
        "Điện thoại",
        "TV màn hình phẳng",
        "Truyền hình vệ tinh",
        "Máy vi tính",
        "TV",
        "Truyền hình trả tiền",
        "Đài radio",
        "Dịch vụ streaming (như là Netflix)",
        "Máy fax",
    ],
    "Dịch vụ lễ tân": [
        "Thu đổi ngoại tệ",
        "Dịch vụ trợ giúp đặc biệt",
        "Nhận/trả phòng cấp tốc",
        "Tủ khóa",
        "Máy ATM/rút tiền trong khuôn viên",
        "Có xuất hóa đơn",
        "Lễ tân 24 giờ",
        "Nhận/trả phòng riêng",
        "Bàn bán tour",
        "Giữ hành lí",
    ],
    "Hồ bơi - ngoài trời (dành cho trẻ em)": [
        "Khăn hồ bơi/bãi biển",
        "Ô (dù) che nắng loại to",
        "Giờ mở cửa",
        "Phù hợp cho trẻ em",
        "Ghế/ghế dài tắm nắng",
        "Mở cửa quanh năm",
        "Chỗ cạn",
    ],
    "2 hồ bơi": [
        "Quầy bar hồ bơi",
        "Chỗ cạn",
        "Mái che hồ bơi",
        "Ghế/ghế dài tắm nắng",
        "Đồ chơi ở hồ bơi",
        "Phù hợp cho trẻ em",
        "Hồ bơi vô cực",
        "Giờ mở cửa",
        "Chỉ dành cho người lớn",
        "Hồ bơi nước mặn",
        "Mở cửa quanh năm",
        "Hồ bơi trên sân thượng",
        "Hồ bơi có tầm nhìn",
        "Dành cho mọi độ tuổi",
        "Khăn hồ bơi/bãi biển",
        "Ô (dù) che nắng loại to",
        "Hàng rào quanh hồ bơi",
    ],
}
