spring.application.name=AI-Hotel
#spring.datasource.url=jdbc:postgresql://dpg-d0h18j49c44c7397dt2g-a.oregon-postgres.render.com:5432/hotelproposal_nkfi
spring.datasource.url=jdbc:postgresql://dpg-d115uhidbo4c739mcaug-a.oregon-postgres.render.com:5432/dntrip
spring.datasource.username=dntrip
spring.datasource.password=DRuqx7mccS4KFzgmbVff3PTbTOIfG3cW
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
#logging.level.org.hibernate=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.data.web.pageable.one-indexed-parameters=true
spring.jpa.show-sql=true


spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080

# JWT Configuration
JWT_SECRET=lKhBN1erZv47gkY241X4U8+zddIzAU2uczvNk5KpN70RwMPxubNTSk1rSEmnP55M
jwt.expiration=86400000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:https://final-pbl-8czd.onrender.com/login/oauth2/code/google}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Facebook OAuth2 Configuration
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.redirect-uri=${FACEBOOK_REDIRECT_URI:https://final-pbl-8czd.onrender.com/login/oauth2/code/facebook}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id

cloudinary.cloud-name=duijhzhz3
cloudinary.api-key=425184687753845
cloudinary.api-secret=zrWhoXIdFYd9hsxJ3KClg8M7J-o

resend.api-key=re_UwUSKQNg_EMC7CsQgrUDzsMzcZwXQfBmx

spring.web.resources.add-mappings=false